### ISSUE TITLE
Update JS files to es6+ standards

### ISSUE THREAD

**Issue by Don-Stevenson** [KCarlile/flashchord#29]

**Comment by Don-Stevenson** [comment]
I see this was covered in a PR below

**Comment by KCarlile** [comment]
@Don-Stevenson, I'm not sure this was handled in a PR. I don't think I've intentionally done this, so we probably still need to do it. I'm definitely still using `$var` and `function()` like you mentioned in your email.

**Comment by KCarlile** [comment]
Oh, maybe you meant issue #24. I'll add your comment here to that issue.

**Comment by KCarlile** [comment]
Re-opening for use with new efforts.
