### ISSUE TITLE
Add @Flash_Chord Twitter link

### ISSUE THREAD

**Issue by KCarlile** [KCarlile/flashchord#34]
## Background
In order for people to follow updates for Flash Chord, we have a Twitter account for announcing new features and other information: https://twitter.com/flash_chord

## Acceptance Criteria
- The Twitter icon followed by the `@Flash_Chord` handle text are linked to https://twitter.com/flash_chord in the footer (copyright section) and on the About page
- The README.md file includes a link to the Twitter account for reference, but without icon

## Approach
- https://twitter.com/flash_chord link as `@Flash_Chord` text
- Prefix the Twitter handle text with the Twitter icon, found here: https://about.twitter.com/en_us/company/brand-resources.html
- Put this link in the copyright footer and also on the About page where appropriate

**Comment by Don-Stevenson** [comment]
Great initiative @KCarlile !

**Comment by KCarlile** [comment]
The Twitter icons required me to generate my own pngs, which I didn't want to do, and I've had good luck with Font Awesome before, so I'm using that instead.

**Comment by Steve-CCity** [comment]
Just tested.  Looks fine.  Works fine.

**Comment by KCarlile** [comment]
Thanks for testing, @Steve-CCity! :)

**Comment by KCarlile** [comment]
Closed in release 1.5.
