### ISSUE TITLE
GitHub identifies somes PHP files as Hacklang

### ISSUE THREAD

**Issue by KCarlile** [KCarlile/flashchord#35]
## Background
In looking at the code makeup of Flash Chord, GitHub seems to think that some of the PHP include files are "hack" as in Hacklang. See: https://github.com/KCarlile/flashchord/search?l=hack

Others have run into this as well: https://github.com/github/linguist/issues/4229

This seems to be resolved by a `.gitattributes` file override: https://github.com/github/linguist#overrides

## Acceptance Criteria
- GitHub no longer lists .php files as Hack on this page: https://github.com/KCarlile/flashchord/search?l=hack

## Approach
- Create a `.gitattributes` file and add an entry for .php files using this model: https://github.com/github/linguist#overrides
- Commit, push, and confirm

**Comment by KCarlile** [comment]
I doubt this will be able to be tested until it's merged into master and GitHub recalculates/rescans the codebase.

**Comment by KCarlile** [comment]
Closed in release 1.5.

**Comment by luisfelipesdn12** [comment]
Now overrides documentation is in: https://github.com/github/linguist/blob/master/docs/overrides.md
